팀 목록 페이지 디자인 디테일 조금
skku-amang/Homepage-FrontEnd pull request #51
Opened 2024-09-08 07:00 UTC by youngjjju

비율을 조정하고, 색깔을 가장 비슷해보이는 zinc 계열로 바꿨습니다. List Cell들 간의 간격을 조정했습니다. 근데 배경색이 디자인에서는 약간 회색이던데 이건 어떻게 하나요? 괜히 건들였다가 다 이상해질 거 같아서 일단 놔뒀습니다.

2024-09-08 12:04 UTC, manamana32321 commented
![image](https://github.com/user-attachments/assets/1c02b913-e0f6-4df8-9455-87c835c5070f)
이제 디자인 팀에서 TailwindCSS의 컬러 파레트를 사용하기 때문에 정확한 색상을 지정할 수 있습니다.
비슷한 색이 아니라 '정확한' 색은 피그마에서 원하는 컴포넌트를 더블클릭 하다 보면 확인할 수 있습니다!

2024-09-08 12:16 UTC, manamana32321 requested changes
고생했슈!

2024-09-08 12:16 UTC, manamana32321 commented on app/(general)/teams/_components/TeamListTable/ui/table.tsx
굳이 `ui`라는 폴더를 따로 만들 필요는 없어 보입니다.
`TeamListTable`로 옮겨주세요

2024-09-09 12:30 UTC, youngjjju commented on app/(general)/teams/_components/TeamListTable/ui/table.tsx
넵

2024-09-09 14:21 UTC, manamana32321 approved these changes
LGTM!

2024-09-09 14:25 UTC, merged